### ISSUE TITLE
The `use_docker` example fails on nokogiri install

### ISSUE THREAD

**Issue by yodarjun** [navarasu/serverless-ruby-layer#30]
**Describe the bug**
I'm using the example listed under the `example/use_docker` directory. I'm using ruby version 2.5.8 for executing this code. However, every time I run `sls package` in the example directory, I get an error with nokogiri. Any help or guidance in this would be awesome.

**Error Stack Trace**
Running `SLS_DEBUG=* sls package`:
```
➜  use_docker git:(master) ✗ SLS_DEBUG=* sls package
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command rubylayer
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Clearing previous build ruby layer build
Serverless: Installing gem using docker bundler
Serverless: [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'test development'`, and stop using this flag
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10/ext/nokogiri
/var/lang/bin/ruby -I /var/lang/lib/ruby/site_ruby/2.5.0 -r
./siteconf20201030-1-7135cl.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.10
with the following patches applied:
        - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
        - 0002-Remove-script-macro-support.patch
        - 0003-Update-entities-to-remove-handling-of-ssi.patch
        - 0004-libxml2.la-is-in-top_builddir.patch
        - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.10.tar.gz into
tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10... ERROR, review
'/var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10/extract.log'
to see what happened. Last lines are:
========================================================================
gtar: libxml2-2.9.10/aclocal.m4: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/testAutomata.c: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/check-relaxng-test-suite2.py: Cannot change ownership to
uid 1000, gid 1000: Operation not permitted
gtar: libxml2-2.9.10/INSTALL: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/xmlcatalog.c: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/vms/config.vms: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/vms/readme.vms: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/vms/build_libxml.com: Cannot change ownership to uid 1000,
gid 1000: Operation not permitted
gtar: libxml2-2.9.10/vms/diffs.vms: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/vms: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/triostr.h: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/tree.c: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/testModule.c: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/relaxng.c: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/libxml2-config.cmake.in: Cannot change ownership to uid
1000, gid 1000: Operation not permitted
gtar: libxml2-2.9.10/Makefile.tests: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10/dict.c: Cannot change ownership to uid 1000, gid 1000:
Operation not permitted
gtar: libxml2-2.9.10/libxml.spec.in: Cannot change ownership to uid 1000, gid
1000: Operation not permitted
gtar: libxml2-2.9.10: Cannot change ownership to uid 1000, gid 1000: Operation
not permitted
gtar: Exiting with failure status due to previous errors
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/var/lang/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:402:in
`block in execute': Failed to complete extract task (RuntimeError)
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
`chdir'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
`execute'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:367:in
`extract_file'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:62:in
`block in extract'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in
`each'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in
`extract'
from
/var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:151:in
`cook'
        from extconf.rb:365:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:364:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/var/gem_build/build/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10 for inspection.
Results logged to
/var/gem_build/build/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.10.10' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  nokogiri


  Error --------------------------------------------------

  Error: [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'test development'`, and stop using this flag
  Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

  current directory:
  /var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10/ext/nokogiri
  /var/lang/bin/ruby -I /var/lang/lib/ruby/site_ruby/2.5.0 -r
  ./siteconf20201030-1-7135cl.rb extconf.rb
  checking if the C compiler accepts ... yes
  Building nokogiri using packaged libraries.
  Using mini_portile version 2.4.0
  checking for gzdopen() in -lz... yes
  checking for iconv... yes
  ************************************************************************
  IMPORTANT NOTICE:

  Building Nokogiri with a packaged version of libxml2-2.9.10
  with the following patches applied:
        - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
        - 0002-Remove-script-macro-support.patch
        - 0003-Update-entities-to-remove-handling-of-ssi.patch
        - 0004-libxml2.la-is-in-top_builddir.patch
        - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch

  Team Nokogiri will keep on doing their best to provide security
  updates in a timely manner, but if this is a concern for you and want
  to use the system library instead; abort this installation process and
  reinstall nokogiri as follows:

      gem install nokogiri -- --use-system-libraries
          [--with-xml2-config=/path/to/xml2-config]
          [--with-xslt-config=/path/to/xslt-config]

  If you are using Bundler, tell it to use the option:

      bundle config build.nokogiri --use-system-libraries
      bundle install

  Note, however, that nokogiri is not fully compatible with arbitrary
  versions of libxml2 provided by OS/package vendors.
  ************************************************************************
  Extracting libxml2-2.9.10.tar.gz into
  tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10... ERROR, review
  '/var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10/extract.log'
  to see what happened. Last lines are:
  ========================================================================
  gtar: libxml2-2.9.10/aclocal.m4: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/testAutomata.c: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/check-relaxng-test-suite2.py: Cannot change ownership to
  uid 1000, gid 1000: Operation not permitted
  gtar: libxml2-2.9.10/INSTALL: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/xmlcatalog.c: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/vms/config.vms: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/vms/readme.vms: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/vms/build_libxml.com: Cannot change ownership to uid 1000,
  gid 1000: Operation not permitted
  gtar: libxml2-2.9.10/vms/diffs.vms: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/vms: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/triostr.h: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/tree.c: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/testModule.c: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/relaxng.c: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/libxml2-config.cmake.in: Cannot change ownership to uid
  1000, gid 1000: Operation not permitted
  gtar: libxml2-2.9.10/Makefile.tests: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10/dict.c: Cannot change ownership to uid 1000, gid 1000:
  Operation not permitted
  gtar: libxml2-2.9.10/libxml.spec.in: Cannot change ownership to uid 1000, gid
  1000: Operation not permitted
  gtar: libxml2-2.9.10: Cannot change ownership to uid 1000, gid 1000: Operation
  not permitted
  gtar: Exiting with failure status due to previous errors
  ========================================================================
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of necessary
  libraries and/or headers.  Check the mkmf.log file for more details.  You may
  need configuration options.

  Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/var/lang/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:402:in
  `block in execute': Failed to complete extract task (RuntimeError)
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
  `chdir'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
  `execute'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:367:in
  `extract_file'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:62:in
  `block in extract'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in
  `each'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in
  `extract'
  from
  /var/gem_build/build/ruby/2.5.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:151:in
  `cook'
        from extconf.rb:365:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:364:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:557:in `<main>'

  To see why this extension failed to compile, please check the mkmf.log which can
  be found here:

  /var/gem_build/build/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.10.10/mkmf.log

  extconf failed, exit code 1

  Gem files will remain installed in
  /var/gem_build/build/ruby/2.5.0/gems/nokogiri-1.10.10 for inspection.
  Results logged to
  /var/gem_build/build/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.10.10/gem_make.out

  An error occurred while installing nokogiri (1.10.10), and Bundler cannot
  continue.
  Make sure that `gem install nokogiri -v '1.10.10' --source
  'https://rubygems.org/'` succeeds before bundling.

  In Gemfile:
    nokogiri

      at runCommand (/Users/arjun/open_source/serverless-ruby-layer/examples/use_docker/node_modules/serverless-ruby-layer/lib/bundle.js:23:11)
      at docker (/Users/arjun/open_source/serverless-ruby-layer/examples/use_docker/node_modules/serverless-ruby-layer/lib/bundle.js:29:12)
      at ServerlessRubyBundler.bundleInstall (/Users/arjun/open_source/serverless-ruby-layer/examples/use_docker/node_modules/serverless-ruby-layer/lib/bundle.js:100:5)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:483:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:518:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:518:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:136:33
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:123:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:54:26
      at processImmediate (internal/timers.js:444:21)
      at process.topLevelDomainCallback (domain.js:134:15)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/scripts/serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:1128:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
      at Module.load (internal/modules/cjs/loader.js:983:32)
      at Function.Module._load (internal/modules/cjs/loader.js:891:14)
      at Module.require (internal/modules/cjs/loader.js:1023:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1128:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
      at Module.load (internal/modules/cjs/loader.js:983:32)
      at Function.Module._load (internal/modules/cjs/loader.js:891:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.3.0
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.3

```

**Example Config files**
I am only running the example folder.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS]
 - NodeVersion v13.3.0
 - Ruby version 2.5.8
 - Bundler version 1.17.2

**Comment by navarasu** [comment]
Thanks, Anand for reporting this issue. Is it a very old docker image? Can you pull the latest and try again,

**Comment by yodarjun** [comment]
Hey @navarasu thanks for replying. I tried doing what you suggested, but I'm still having the same issue.

```
➜  use_docker git:(master) ✗ docker image pull lambci/lambda:build-ruby2.5
build-ruby2.5: Pulling from lambci/lambda
Digest: sha256:26c1d3de7621d2bad3f439c45723f3604f0651d9c018aa64d269ef6326baa33a
Status: Image is up to date for lambci/lambda:build-ruby2.5
docker.io/lambci/lambda:build-ruby2.5
```

**Comment by navarasu** [comment]
Interesting. Not sure why it is not working on your machine with the same docker image.

This is my docker version.
```
➜  ~ docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 Not sure the docker version is the issue. Try updating your docker as well.
 Also, try removing the image (`docker image rm -f lambci/lambda:build-ruby2.5`) and run `sls deploy` again

**Comment by yodarjun** [comment]
Still getting the same error after I do that :-/ What version of serverless should I be using? I've tried 1.7 and also 2.9.0

**Comment by navarasu** [comment]
@yodarjun , I tried reproducing the same in different machines. It works in all cases. 
Alternatively, you can configure your own docker file. Refer pg gem example [here](https://github.com/navarasu/serverless-ruby-layer/tree/master/examples/use_docker_file). Similarly, you can add the necessary native library to fix nokogiri issue.

**Comment by navarasu** [comment]
@yodarjun I think this might be an issue related to volume mount but not sure. Please update to the latest version 1.4.0 and verify again.
